/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_asu_smarthome_smartgateway_lighting
#define DBUS_GLIB_CLIENT_WRAPPERS_org_asu_smarthome_smartgateway_lighting

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_asu_smarthome_smartgateway_lighting_get_status (DBusGProxy *proxy, gint* OUT_cur_status, GError **error)

{
  return dbus_g_proxy_call (proxy, "getStatus", error, G_TYPE_INVALID, G_TYPE_INT, OUT_cur_status, G_TYPE_INVALID);
}

typedef void (*org_asu_smarthome_smartgateway_lighting_get_status_reply) (DBusGProxy *proxy, gint OUT_cur_status, GError *error, gpointer userdata);

static void
org_asu_smarthome_smartgateway_lighting_get_status_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_cur_status;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_cur_status, G_TYPE_INVALID);
  (*(org_asu_smarthome_smartgateway_lighting_get_status_reply)data->cb) (proxy, OUT_cur_status, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_asu_smarthome_smartgateway_lighting_get_status_async (DBusGProxy *proxy, org_asu_smarthome_smartgateway_lighting_get_status_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getStatus", org_asu_smarthome_smartgateway_lighting_get_status_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_asu_smarthome_smartgateway_lighting_set_status (DBusGProxy *proxy, const gint IN_new_status, GError **error)

{
  return dbus_g_proxy_call (proxy, "setStatus", error, G_TYPE_INT, IN_new_status, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_asu_smarthome_smartgateway_lighting_set_status_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_asu_smarthome_smartgateway_lighting_set_status_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_asu_smarthome_smartgateway_lighting_set_status_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_asu_smarthome_smartgateway_lighting_set_status_async (DBusGProxy *proxy, const gint IN_new_status, org_asu_smarthome_smartgateway_lighting_set_status_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "setStatus", org_asu_smarthome_smartgateway_lighting_set_status_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INT, IN_new_status, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_asu_smarthome_smartgateway_lighting */

G_END_DECLS
