g++ -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp -lmicrohttpd /usr/lib/libboost_regex.a

g++ `pkg-config --cflags dbus-glib-1` -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp DeviceCatalog.cpp -lmicrohttpd /usr/lib/libboost_regex.a `pkg-config --libs dbus-glib-1`

g++ `pkg-config --cflags dbus-glib-1` -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp DeviceCatalog.cpp -lmicrohttpd /usr/lib/libboost_regex.a `pkg-config --libs dbus-glib-1` -lboost_system -lboost_filesystem

 g++ `pkg-config --cflags dbus-glib-1` -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp DeviceCatalog.cpp -Wl,-rpath=/usr/local/lib -lmicrohttpd /usr/lib/libboost_regex.a `pkg-config --libs dbus-glib-1` -lboost_system -lboost_filesystem

g++ `pkg-config --cflags dbus-glib-1` -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp OntologyManager.cpp DeviceCatalog.cpp  /usr/lib/libboost_regex.a  -I /home/shankar/owlcpp-master/include -I /home/shankar/owlcpp-master/out/include -I ~/boost_1_55_0/ -L /home/shankar/owlcpp-master/out/bin/rdf/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/logic/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/io/gcc-4.6/release/link-static -L ~/boost_1_55_0/bin.v2/libs/filesystem/build/gcc-4.6/debug/link-static/ -L ~/boost_1_55_0/bin.v2/libs/program_options/build/gcc-4.6/debug/link-static/ -L /usr/local/lib/ -L /home/shankar/FaCT++-1.6.1/src/Kernel -L /home/shankar/owlcpp-master/out/bin/rdf/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/logic/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/io/gcc-4.6/release/link-static `pkg-config --libs dbus-glib-1` -lmicrohttpd -lboost_system -lboost_filesystem -lKernel -lowlcpp_io -lowlcpp_logic -lowlcpp_rdf -lraptor2 -lboost_filesystem -lboost_program_options -lboost_system

/home/shankar/owlcpp-master/out/ext/factpp/factpp/gcc-4.6/release/link-static -lfactpp_kernel
/home/shankar/owlcpp-master/out/ext/raptor/raptor/gcc-4.6/release/link-static/raptor-version-2.0.8/ -lraptor
/home/shankar/owlcpp-master/out/ext/libxml2/libxml2/gcc-4.6/release/libxml2-version-2.9.0/link-static -lxml2

g++ `pkg-config --cflags dbus-glib-1` -o http_rest_server httphandler.cpp RestAPI.cpp Executor.cpp strutil.cpp OntologyManager.cpp DeviceCatalog.cpp  /usr/lib/libboost_regex.a  -I /home/shankar/owlcpp-master/include -I /home/shankar/owlcpp-master/out/include -I ~/boost_1_55_0/ -L /home/shankar/owlcpp-master/out/bin/rdf/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/logic/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/io/gcc-4.6/release/link-static -L ~/boost_1_55_0/bin.v2/libs/filesystem/build/gcc-4.6/debug/link-static/ -L ~/boost_1_55_0/bin.v2/libs/program_options/build/gcc-4.6/debug/link-static/ -L /usr/local/lib/ -L /home/shankar/owlcpp-master/out/ext/factpp/factpp/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/rdf/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/logic/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/bin/io/gcc-4.6/release/link-static -L /home/shankar/owlcpp-master/out/ext/libxml2/libxml2/gcc-4.6/release/libxml2-version-2.9.0/link-static -L /home/shankar/owlcpp-master/out/ext/raptor/raptor/gcc-4.6/release/link-static/raptor-version-2.0.8/ `pkg-config --libs dbus-glib-1` -lmicrohttpd -lfactpp_kernel -lowlcpp_io -lowlcpp_logic -lowlcpp_rdf -lraptor -lxml2 -lboost_filesystem -lboost_program_options -lboost_system
